language: node_js

node_js:
  - "stable"
  - "lts/*"


before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn run dev-install
  - yarn test
  - yarn run check-format
